apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
  namespace: micro-demo
  labels:
    app.kubernetes.io/name: inventory-service
    app.kubernetes.io/part-of: micro-demo
data:
  PORT: "3001"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
